# Generated by Django 3.1.2 on 2020-10-26 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=255)),
                ('type', models.CharField(choices=[('BMS', 'Breads, Muffins, and Scones'), ('BR', 'Breakfast'), ('DST', 'Desserts'), ('DIN', 'Dinner'), ('DR', 'Drinks'), ('LN', 'Lunch'), ('SD', 'Sides')], default='', max_length=4)),
                ('prep_time', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2880)])),
                ('cook_time', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2880)])),
                ('cook_temp', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('temp_format', models.CharField(choices=[('F', '°F'), ('C', '°C')], default='F', max_length=1)),
                ('amount', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('serving', models.CharField(max_length=255)),
            ],
        ),
    ]
