# Generated by Django 3.1.2 on 2020-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('BMS', 'Breads, Muffins, and Scones'), ('BR', 'Breakfast'), ('DST', 'Desserts'), ('DIN', 'Dinner'), ('DR', 'Drinks'), ('LN', 'Lunch'), ('SD', 'Sides')], max_length=4),
        ),
    ]
