# Generated by Django 3.1.2 on 2020-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201026_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.TimeField(),
        ),
    ]
