# Generated by Django 3.1.2 on 2020-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201029_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(default=None),
        ),
    ]
