# Generated by Django 3.1.2 on 2020-10-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='type',
            new_name='recipe_type',
        ),
    ]
