# Generated by Django 3.1.2 on 2020-10-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20201029_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(default='https://www.macmillandictionary.com/external/slideshow/thumb/Grey_thumb.png', max_length=255),
        ),
    ]
